# Generated by Django 5.0.7 on 2024-07-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('coverURL', models.CharField(max_length=200)),
                ('firstPublishDate', models.PositiveSmallIntegerField()),
                ('onShelf', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
